"""initial baseline

Revision ID: e489c8788336
Revises: 
Create Date: 2026-06-18 13:22:24.705292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e489c8788336'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_levels_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_levels_name'), ['name'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('candidate_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('specialty_summary', sa.Text(), nullable=True),
    sa.Column('suitability_suggestion', sa.Text(), nullable=True),
    sa.Column('hr_note', sa.Text(), nullable=True),
    sa.Column('is_strong', sa.Boolean(), nullable=False),
    sa.Column('cv_text', sa.Text(), nullable=True),
    sa.Column('cv_file_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_profiles_id'), ['id'], unique=False)

    op.create_table('candidate_digital_twins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('predicted_level', sa.String(length=255), nullable=True),
    sa.Column('level_confidence', sa.Float(), nullable=True),
    sa.Column('predicted_roles', sa.JSON(), nullable=True),
    sa.Column('strengths_analysis', sa.JSON(), nullable=True),
    sa.Column('hidden_skills', sa.JSON(), nullable=True),
    sa.Column('growth_potential', sa.String(length=255), nullable=True),
    sa.Column('growth_reasoning', sa.Text(), nullable=True),
    sa.Column('recommended_paths', sa.JSON(), nullable=True),
    sa.Column('interview_questions', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_digital_twins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_digital_twins_candidate_id'), ['candidate_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_candidate_digital_twins_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_digital_twins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_digital_twins_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_digital_twins_candidate_id'))

    op.drop_table('candidate_digital_twins')
    with op.batch_alter_table('candidate_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_profiles_id'))

    op.drop_table('candidate_profiles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))
        batch_op.drop_index(batch_op.f('ix_roles_id'))

    op.drop_table('roles')
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_levels_name'))
        batch_op.drop_index(batch_op.f('ix_levels_id'))

    op.drop_table('levels')
    # ### end Alembic commands ###
